services:
  composer:
    image: composer:2
    working_dir: /app
    volumes:
      - ./:/app
  php:
    image: php:8.4-cli
    working_dir: /app
    volumes:
      - ./:/app
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"
